# minimal_browser_list: &minimal_browser_list
#   - chrome
#   - firefox

# extended_browser_list: &extended_browser_list
#   - chrome
#   - firefox
#   - edge

tests:
  # API
  - test_name: integ_next_api_data_client_gen2
    desc: Next.js Data Client Gen 2
    framework: next
    category: api
    sample_name: [data-client-gen2]
    spec: data-client-gen2
    browser: [chrome] # Issues using Auth category / setting secure cookies in FF using Cypress with a Next.js app. Manual testing in FF works as expected
