name: Load Verdaccio with amplify-data
description: Turn on Verdaccio and load up all of the amplify-data build artifacts

runs:
  using: 'composite'
  steps:
    - name: Start verdaccio
      # While / sleep are required here, as Verdaccio takes a minute to start:
      run: |
        npm run vend
        while ! nc -z localhost 4873; do
          echo "Verdaccio not running yet"
          sleep 1
        done

        # Run your commands after verdaccio is up and running
        echo "Verdaccio is up and running, proceeding with the script..."
      shell: bash
      working-directory: ./amplify-data
    - name: Upload artifact
      uses: actions/upload-artifact@v4 # v4 https://github.com/actions/upload-artifact
      if: failure()
      with:
        name: ${{ inputs.test_name }}-npm-log
        if-no-files-found: ignore
        path: /Users/runner/.npm/_logs/
        retention-days: 3
