import fs from 'fs/promises';
import path from 'path';
import { outputsFileName } from '../utils/';

/**
 * `amplify_outputs.json` is generated by the `deploySandbox` function,
 * therefore we need to verify that it was generated, and import it here.
 */
export const getGeneratedOutputs = async (sandboxDir: string) => {
  const filePath = path.join(
    `./amplify-backends/${sandboxDir}/`,
    outputsFileName,
  );

  try {
    // Check that the file exists:
    const clientConfigStats = await fs.stat(filePath);
    const isFile = await clientConfigStats.isFile();

    if (!isFile) {
      throw new Error('Amplify outputs not generated');
    }

    const relativeImportPath = path.join(
      `../amplify-backends/${sandboxDir}/`,
      outputsFileName,
    );
    const result = await import(relativeImportPath);
    const outputs = result.default;
    return { result: outputs };
  } catch (error) {
    return { errors: error };
  }
};
