import { bench } from '@arktype/attest';
import { a, ClientSchema } from '@aws-amplify/data-schema';

bench('baseline', () => {}).types([0, 'instantiations']);

/**
 * The following benchmarks are for testing different permutations of
 * large production-level schemas ("p10").
 * Permutations include many models with fewer fields, fewer models with many
 * fields, and a mix of both.
 * "Complex" models contain connections, as well as global, model-level, and
 * field-level auth rules.
 * "Simple" models have no connections, and only global public auth rules.
 * (TODO) Each schema represented here has been evaluated to result in roughly
 * the same field and / or type count when it is generated as an AppSync GraphQL
 * Schema.
 */

// [TODO]: reference metrics
bench('1 simple model w/ 1700 fields each', () => {
  a.schema({
    Model1: a.model({
      field1: a.string(),
      field2: a.string(),
      field3: a.string(),
      field4: a.string(),
      field5: a.string(),
      field6: a.string(),
      field7: a.string(),
      field8: a.string(),
      field9: a.string(),
      field10: a.string(),
      field11: a.string(),
      field12: a.string(),
      field13: a.string(),
      field14: a.string(),
      field15: a.string(),
      field16: a.string(),
      field17: a.string(),
      field18: a.string(),
      field19: a.string(),
      field20: a.string(),
      field21: a.string(),
      field22: a.string(),
      field23: a.string(),
      field24: a.string(),
      field25: a.string(),
      field26: a.string(),
      field27: a.string(),
      field28: a.string(),
      field29: a.string(),
      field30: a.string(),
      field31: a.string(),
      field32: a.string(),
      field33: a.string(),
      field34: a.string(),
      field35: a.string(),
      field36: a.string(),
      field37: a.string(),
      field38: a.string(),
      field39: a.string(),
      field40: a.string(),
      field41: a.string(),
      field42: a.string(),
      field43: a.string(),
      field44: a.string(),
      field45: a.string(),
      field46: a.string(),
      field47: a.string(),
      field48: a.string(),
      field49: a.string(),
      field50: a.string(),
      field51: a.string(),
      field52: a.string(),
      field53: a.string(),
      field54: a.string(),
      field55: a.string(),
      field56: a.string(),
      field57: a.string(),
      field58: a.string(),
      field59: a.string(),
      field60: a.string(),
      field61: a.string(),
      field62: a.string(),
      field63: a.string(),
      field64: a.string(),
      field65: a.string(),
      field66: a.string(),
      field67: a.string(),
      field68: a.string(),
      field69: a.string(),
      field70: a.string(),
      field71: a.string(),
      field72: a.string(),
      field73: a.string(),
      field74: a.string(),
      field75: a.string(),
      field76: a.string(),
      field77: a.string(),
      field78: a.string(),
      field79: a.string(),
      field80: a.string(),
      field81: a.string(),
      field82: a.string(),
      field83: a.string(),
      field84: a.string(),
      field85: a.string(),
      field86: a.string(),
      field87: a.string(),
      field88: a.string(),
      field89: a.string(),
      field90: a.string(),
      field91: a.string(),
      field92: a.string(),
      field93: a.string(),
      field94: a.string(),
      field95: a.string(),
      field96: a.string(),
      field97: a.string(),
      field98: a.string(),
      field99: a.string(),
      field100: a.string(),
    }),
  }).authorization([a.allow.public()]);
}).types([4639, 'instantiations']);
