name: Prebuild AmplifyJsSamplesStaging

on:
  workflow_call:
    secrets:
      AMPLIFY_JS_SAMPLES_STAGING_READ:
        required: true
jobs:
  pre-staging:
    name: Prebuild Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: amplify-data
      - name: Setup samples staging
        uses: ./amplify-data/.github/actions/setup-samples-staging
        with:
          AMPLIFY_JS_SAMPLES_STAGING_READ: ${{ secrets.AMPLIFY_JS_SAMPLES_STAGING_READ }}
