name: Unit Tests

on:
  workflow_call:
    inputs:
      tsVersion:
        required: true
        type: string
jobs:
  unit_test:
    name: Lint & Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
        with:
          path: amplify-data
      - name: Install specific typescript version
        env:
          VERSION: ${{ inputs.tsVersion }}
        working-directory: ./amplify-data
        run: npm i typescript@$VERSION
      - name: Setup node and build the repository
        uses: ./amplify-data/.github/actions/node-and-build
        with:
          force: true
      - name: Run tests
        working-directory: ./amplify-data
        run: npm run lint && npm run test
