name: E2E Test - Detox
run-name: e2e-detox.${{ inputs.test_name }}

on:
  workflow_call:
    inputs:
      test_name:
        required: true
        type: string
      working_directory:
        required: true
        type: string
      timeout_minutes:
        required: true
        type: number

jobs:
  e2e-test:
    name: E2E-Detox ${{ inputs.test_name }}
    runs-on: macos-latest
    timeout-minutes: ${{ inputs.timeout_minutes }}

    steps:
      - name: Checkout repository
        # TODO:
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          # TODO:
          path: amplify-api-next
      - name: Setup node and build the repository
        # TODO:
        uses: ./amplify-api-next/.github/actions/node-and-build
      - name: Setup samples staging repository
        # TODO:
        uses: ./amplify-api-next/.github/actions/setup-samples-staging
        with:
          AMPLIFY_JS_SAMPLES_STAGING_READ: ${{ secrets.AMPLIFY_JS_SAMPLES_STAGING_READ }}
      - name: Load Verdaccio with amplify-api-next
        # TODO:
        uses: ./amplify-api-next/.github/actions/load-verdaccio-with-amplify-api-next
      - name: Yarn Install
        working-directory: ${{ inputs.working_directory }}
        run: |
          echo "Current NPM registry: " $(yarn config get registry)
          $GITHUB_WORKSPACE/amplify-api-next/scripts/retry-yarn-script.sh -s 'install --frozen-lockfile --non-interactive' -n 3
        shell: bash
      - name: Install CocoaPods
        run: |
          cd ios && pod install
        working-directory: ${{ inputs.working_directory }}
        shell: bash
      - name: Start iOS simulator (background)
        run: |
          xcrun simctl boot "iPhone 15" &
        shell: bash
      - name: Start Metro Packager (background)
        run: |
          yarn start &
        working-directory: ${{ inputs.working_directory }}
        shell: bash
      - name: Configure Detox
        env:
          HOMEBREW_NO_AUTO_UPDATE: '1'
        run: |
          brew tap wix/brew
          brew install applesimutils
          yarn global add detox-cli
        working-directory: ${{ inputs.working_directory }}
        shell: bash
      - name: Detox Build
        run: |
          detox build -c ios.sim.debug
        env:
          JEST_JUNIT_OUTPUT_DIR: reports/junit
          JEST_JUNIT_OUTPUT_NAME: detox-test-results.xml
        working-directory: ${{ inputs.working_directory }}
        shell: bash
      - name: Detox run
        # TODO:
        run: |
          $GITHUB_WORKSPACE/amplify-api-next/scripts/retry-yarn-script.sh -s 'detox test -c ios.sim.debug -u' -n 3
        working-directory: ${{ inputs.working_directory }}
        shell: bash
