name: Prebuild amplify-api-next

on:
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string

jobs:
  prebuild:
    name: Prebuild on ${{ inputs.runs_on }}
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: Checkout repository
        # TODO: verify upgrade:
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          path: amplify-api-next
      - name: Setup node and build the repository
        uses: ./amplify-api-next/.github/actions/node-and-build
        with:
          is-prebuild: true
