name: Prebuild amplify-api-next

on:
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string

jobs:
  prebuild:
    name: Prebuild on ${{ inputs.runs_on }}
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
        with:
          path: amplify-api-next
      - name: Setup node and build the repository
        uses: ./amplify-api-next/.github/actions/node-and-build
        with:
          is-prebuild: true
