name: Unit Tests

on:
  workflow_call:
    inputs:
      tsVersion:
        required: true
        type: string

permissions:
  contents: read

jobs:
  unit_test:
    name: Lint & Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: amplify-data
      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
      - name: Enable Corepack for Yarn 4
        run: corepack enable
      - name: Install specific typescript version
        env:
          VERSION: ${{ inputs.tsVersion }}
        working-directory: ./amplify-data
        run: yarn add typescript@$VERSION
      - name: Setup node and build the repository
        uses: ./amplify-data/.github/actions/node-and-build
        with:
          force: true
      - name: Run tests
        working-directory: ./amplify-data
        run: yarn lint && yarn test
