name: E2E Tests

on: workflow_call

jobs:
  e2e-prep:
    name: Get E2E test config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          path: amplify-api-next
      - name: Read integ config files
        id: load_config
        run: |
          echo "INTEG_CONFIG=$(cat .github/integ-config/integ-all.yml | yq '.tests' -o=json | jq -c .)" >> $GITHUB_OUTPUT
          echo "DETOX_INTEG_CONFIG=$(cat .github/integ-config/detox-integ-all.yml | yq -o=json | jq -c .)" >> $GITHUB_OUTPUT
        working-directory: ./amplify-api-next
    outputs:
      integ-config: ${{ steps.load_config.outputs.INTEG_CONFIG }}
      detox-integ-config: ${{ steps.load_config.outputs.DETOX_INTEG_CONFIG }}

  e2e-test-runner:
    name: E2E test runnner
    needs: e2e-prep
    secrets: inherit
    strategy:
      matrix:
        integ-config: ${{ fromJson(needs.e2e-prep.outputs.integ-config) }}
      fail-fast: false
    uses: ./.github/workflows/callable-e2e-test.yml
    with:
      test_name: ${{ matrix.integ-config.test_name }}
      framework: ${{ matrix.integ-config.framework }}
      category: ${{ matrix.integ-config.category }}
      spec: ${{ matrix.integ-config.spec || '' }}
      amplifyjs_dir: ${{ matrix.integ-config.amplifyjs_dir || false }}
      sample_name: ${{ toJSON(matrix.integ-config.sample_name) || '[""]' }}
      browser: ${{ toJSON(matrix.integ-config.browser) || '[""]' }}
      backend: ${{ matrix.integ-config.backend }}
      timeout_minutes: ${{ matrix.integ-config.timeout_minutes || 35 }}
      retry_count: ${{ matrix.integ-config.retry_count || 3 }}
      yarn_script: ${{ matrix.integ-config.yarn_script || '' }}

  detox-e2e-test-runner:
    name: E2E test runner
    needs: e2e-prep
    strategy:
      matrix:
        integ-config: ${{ fromJson(needs.e2e-prep.outputs.detox-integ-config) }}
      fail-fast: false
    secrets: inherit
    uses: ./.github/workflows/callable-e2e-test-detox.yml
    with:
      test_name: ${{ matrix.integ-config.test_name }}
      working_directory: ${{ matrix.integ-config.working_directory }}
      timeout_minutes: ${{ matrix.integ-config.timeout_minutes || 45 }}
