name: Set Node and Build
description: Checks out Amplify and builds the package
inputs:
  is-prebuild:
    required: false
    default: false
  force:
    required: false
    default: false
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js 20
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.9 https://github.com/actions/setup-node/commit/1e60f620b9541d16bece96c5465dc8ee9832be0b
      with:
        node-version: 20
      env:
        SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
    - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
      id: cache-build-artifacts
      with:
        path: |
          **/node_modules
          **/dist/
        key: ${{ runner.os }}-build-artifacts-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-build-artifacts-
      env:
        SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
    - name: Force Install
      if: inputs.force == 'true'
      run: npm i --force
      shell: bash
      working-directory: ./amplify-api-next
    # TODO We should be able to skip yarn / bootstrap if we cache enough things. Leaving because skipping causes issues.
    - name: Install
      if: inputs.force != 'true' && (inputs.is-prebuild != 'true' || steps.cache-build-artifacts.outputs.cache-hit != 'true')
      run: npm i
      shell: bash
      working-directory: ./amplify-api-next
    - name: Build packages
      if: steps.cache-build-artifacts.outputs.cache-hit != 'true'
      run: npm run build
      shell: bash
      working-directory: ./amplify-api-next
